import type { ProviderRuntimeModel } from "openclaw/plugin-sdk/plugin-entry";

const PROVIDER_ID = "crof";
export const CROF_BASE_URL = "https://crof.ai/v1";

const CROF_MODELS: ProviderRuntimeModel[] = [
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.30, output: 0.50, cacheRead: 0.003, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
  },
  {
    id: "deepseek-v4-pro-precision",
    name: "DeepSeek V4 Pro (Precision)",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.70, output: 1.40, cacheRead: 0.006, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.12, output: 0.21, cacheRead: 0.003, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.28, output: 0.38, cacheRead: 0.06, cacheWrite: 0 },
    contextWindow: 163_840,
    maxTokens: 163_840,
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.50, output: 1.50, cacheRead: 0.10, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
  },
  {
    id: "mimo-v2.5-pro-precision",
    name: "MiMo V2.5 Pro (Precision)",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.80, output: 2.50, cacheRead: 0.16, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
  },
  {
    id: "glm-5.1",
    name: "GLM 5.1",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.45, output: 2.10, cacheRead: 0.09, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
  },
  {
    id: "glm-5.1-precision",
    name: "GLM 5.1 (Precision)",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.75, output: 2.90, cacheRead: 0.15, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
  },
  {
    id: "greg",
    name: "Greg",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.10, output: 0.20, cacheRead: 0.02, cacheWrite: 0 },
    contextWindow: 229_376,
    maxTokens: 229_376,
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.50, output: 1.99, cacheRead: 0.10, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
  },
  {
    id: "kimi-k2.6-precision",
    name: "Kimi K2.6 (Precision)",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.55, output: 2.70, cacheRead: 0.11, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.35, output: 1.70, cacheRead: 0.07, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
  },
  {
    id: "kimi-k2.5-lightning",
    name: "Kimi K2.5 (Lightning)",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 1.00, output: 3.00, cacheRead: 0.20, cacheWrite: 0 },
    contextWindow: 131_072,
    maxTokens: 32_768,
  },
  {
    id: "glm-5",
    name: "GLM 5",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.48, output: 1.90, cacheRead: 0.10, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
  },
  {
    id: "glm-4.7",
    name: "GLM 4.7",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.25, output: 1.10, cacheRead: 0.05, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
  },
  {
    id: "glm-4.7-flash",
    name: "GLM 4.7 Flash",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.04, output: 0.30, cacheRead: 0.008, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 131_072,
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.10, output: 0.30, cacheRead: 0.02, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax M2.5",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.11, output: 0.95, cacheRead: 0.02, cacheWrite: 0 },
    contextWindow: 204_800,
    maxTokens: 131_072,
  },
  {
    id: "qwen3.6-27b",
    name: "Qwen3.6 27B",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.20, output: 1.50, cacheRead: 0.04, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B A17B",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.35, output: 1.75, cacheRead: 0.07, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5 9B",
    provider: PROVIDER_ID,
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.04, output: 0.15, cacheRead: 0.008, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
  },
];

const CROF_DEFAULT_MODEL = CROF_MODELS[0];
export const CROF_DEFAULT_MODEL_REF: ProviderRuntimeModel = CROF_DEFAULT_MODEL;

export function listCrofModelCatalogEntries(): ProviderRuntimeModel[] {
  return CROF_MODELS.map((m) => ({ ...m }));
}

export function resolveCrofModel(modelId: string): ProviderRuntimeModel | undefined {
  return CROF_MODELS.find((m) => m.id === modelId.trim());
}
