import type { ModelDefinitionConfig, ModelProviderConfig } from "openclaw/plugin-sdk/provider-model-shared";

const PROVIDER_ID = "crof";
export const CROF_BASE_URL = "https://crof.ai/v1";

const CROF_BASE_COMPAT = {
  supportsDeveloperRole: false,
  supportsUsageInStreaming: true,
  supportsStrictMode: false,
  maxTokensField: "max_tokens" as const,
};

export const CROF_MODEL_CATALOG: ModelDefinitionConfig[] = [
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.30, output: 0.50, cacheRead: 0.003, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "deepseek-v4-pro-precision",
    name: "DeepSeek V4 Pro (Precision)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.70, output: 1.40, cacheRead: 0.006, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.12, output: 0.21, cacheRead: 0.003, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.28, output: 0.38, cacheRead: 0.06, cacheWrite: 0 },
    contextWindow: 163_840,
    maxTokens: 163_840,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.50, output: 1.50, cacheRead: 0.10, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "mimo-v2.5-pro-precision",
    name: "MiMo V2.5 Pro (Precision)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.80, output: 2.50, cacheRead: 0.16, cacheWrite: 0 },
    contextWindow: 1_000_000,
    maxTokens: 131_072,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "glm-5.1",
    name: "GLM 5.1",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.45, output: 2.10, cacheRead: 0.09, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "glm-5.1-precision",
    name: "GLM 5.1 (Precision)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.75, output: 2.90, cacheRead: 0.15, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "greg",
    name: "Greg",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.10, output: 0.20, cacheRead: 0.02, cacheWrite: 0 },
    contextWindow: 229_376,
    maxTokens: 229_376,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.50, output: 1.99, cacheRead: 0.10, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "kimi-k2.6-precision",
    name: "Kimi K2.6 (Precision)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.55, output: 2.70, cacheRead: 0.11, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.35, output: 1.70, cacheRead: 0.07, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "kimi-k2.5-lightning",
    name: "Kimi K2.5 (Lightning)",
    reasoning: true,
    input: ["text"],
    cost: { input: 1.00, output: 3.00, cacheRead: 0.20, cacheWrite: 0 },
    contextWindow: 131_072,
    maxTokens: 32_768,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "glm-5",
    name: "GLM 5",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.48, output: 1.90, cacheRead: 0.10, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "glm-4.7",
    name: "GLM 4.7",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.25, output: 1.10, cacheRead: 0.05, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 202_752,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "glm-4.7-flash",
    name: "GLM 4.7 Flash",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.04, output: 0.30, cacheRead: 0.008, cacheWrite: 0 },
    contextWindow: 202_752,
    maxTokens: 131_072,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.10, output: 0.30, cacheRead: 0.02, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax M2.5",
    reasoning: false,
    input: ["text"],
    cost: { input: 0.11, output: 0.95, cacheRead: 0.02, cacheWrite: 0 },
    contextWindow: 204_800,
    maxTokens: 131_072,
    compat: CROF_BASE_COMPAT,
  },
  {
    id: "qwen3.6-27b",
    name: "Qwen3.6 27B",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.20, output: 1.50, cacheRead: 0.04, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B A17B",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.35, output: 1.75, cacheRead: 0.07, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5 9B",
    reasoning: true,
    input: ["text"],
    cost: { input: 0.04, output: 0.15, cacheRead: 0.008, cacheWrite: 0 },
    contextWindow: 262_144,
    maxTokens: 262_144,
    compat: { ...CROF_BASE_COMPAT, supportsReasoningEffort: true },
  },
];

export const CROF_DEFAULT_MODEL_REF = "crof/deepseek-v4-pro";

export function buildCrofModelDefinition(
  model: (typeof CROF_MODEL_CATALOG)[number],
): ModelDefinitionConfig {
  return {
    ...model,
    api: "openai-completions",
  };
}

export function buildCrofProvider(): ModelProviderConfig {
  return {
    baseUrl: CROF_BASE_URL,
    api: "openai-completions",
    models: CROF_MODEL_CATALOG.map(buildCrofModelDefinition),
  };
}
